### ISSUE TITLE
Process for handling translation requests

### ISSUE THREAD

**Issue by xaur** [artikozel/decred-translations#8]
To begin with it, some possible steps are:

* Someone decides that translating article X to a set of languages L is a good idea
* He submits a request to the translators group where he must justify why it should be done
* The group reviews the request and decides whether it is appropriate to allocate resources on it (time and funds), or not, and when
* ...
* After the initial translation is finished, let several people review it (discussion: #6)

**Comment by artikozel** [comment]
Excellent work. Incorporated in the [README](https://github.com/artikozel/decred-translations/blob/master/README.md). Thank you!
