### ISSUE TITLE
Criteria and priorities of what to translate

### ISSUE THREAD

**Issue by xaur** [artikozel/decred-translations#9]
Discussed [here](https://matrix.to/#/!lbzTjhzNbIaDbuAxkS:decred.org/$154502329444522sEmBE:decred.org), some ideas voiced:

* prioritize time-sensitive articles like an epic press release
* fundamental articles must be available in any language, the more they are timeless the better
* prioritize languages/countries where there is no widespread knowledge of English (related+discussion: #5)
* prioritize simpler and not-too-technical articles because many developers speak English
* articles that have something new to say, or explain an existing aspect/feature of Decred in a way that expands the knowledge base available to the average user (from the [README](https://github.com/artikozel/decred-translations/blob/master/README.md))

**Comment by artikozel** [comment]
Good stuff. Incorporated into the [README](https://github.com/artikozel/decred-translations/blob/master/README.md).
